POST http://localhost:3000/api/produtos/ HTTP/1.1
Content-Type: application/json

{
  "categoria": "Racoes",
  "titulo": "Grand Plus Filote",
  "descripcao": "Racoes para chachorro filote",
  "valor": 90
}

###
DELETE http://localhost:3000/api/produtos/63151326700d2f3c387ac2fe HTTP/1.1

###
GET http://localhost:3000/api/produtos/63151329cd9c6f4ff048a84e HTTP/1.1

###
GET http://localhost:3000/api/produtos/ HTTP/1.1

###
PUT http://localhost:3000/api/produtos/63151329cd9c6f4ff048a84e HTTP/1.1
Content-Type: application/json

{
  "categoria": "Racoes",
  "titulo": "Grand Plus Filote 20 Kg",
  "descripcao": "Racoes para chachorro filote",
  "valor": 200
}